dev_directory : ./dev_data
eval_directory : ./eval_data
model_directory: ./model
result_directory: ./result
result_file: result.csv


target_dir : E:\ml\hw5\
denoise:
  area_removed_size_t1 : 50
  kernel_size_t1 : 4
  area_removed_size_t2 : 50
  kernel_size_t2 : 2
  area_removed_size_t3 : 50
  kernel_size_t3 : 2

fit:
  lr : 0.001
  epochs_t1 : 100
  epochs_t2 : 400
  epochs_t3 : 400
  batch_size : 10

test:
  batch_size : 1
